<?php
$modversion['name'] = _XF_XFTROVE_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _XF_XFTROVE_DESC;
$modversion['author'] = "Arjen van Efferen (http://xoopsforge.mediacom4.net)";
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "";
$modversion['license'] = "GPL";
$modversion['official'] = 0;
$modversion['image'] = "images/xftrove.png";
$modversion['dirname'] = "xftrove";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xf_trove_agg";
$modversion['tables'][1] = "xf_trove_cat";
$modversion['tables'][2] = "xf_trove_group_link";
$modversion['tables'][3] = "xf_trove_treesums";

// Admin things
$modversion['hasAdmin'] = 0;

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = _XF_XFTROVE_SUB1;
//$modversion['sub'][1]['url'] = "project_list.php";
//$modversion['sub'][2]['name'] = _XF_XFTROVE_SUB2;
//$modversion['sub'][2]['url'] = "trove_list.php";


// templates
$modversion['templates'][1]['file'] = 'xftrove_trove_list.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xftrove_project_list.html';
$modversion['templates'][2]['description'] = '';


?>