<?php
$modversion['name'] = _XF_XFSNIPPET_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _XF_XFSNIPPET_DESC;
$modversion['author'] = "Arjen van Efferen (http://xoopsforge.mediacom4.net)";
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "";
$modversion['license'] = "GPL";
$modversion['official'] = 0;
$modversion['image'] = "images/xfsnippet.png";
$modversion['dirname'] = "xfsnippet";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// Tables created by sql file (without prefix!)

$modversion['templates'][1]['file'] = 'xfsnippet_index.html';
$modversion['templates'][1]['description'] = '';

$modversion['tables'] [0] = " xf_snippet";
$modversion['tables'] [1] = " xf_snippet_category";
$modversion['tables'] [2] = " xf_snippet_language";
$modversion['tables'] [3] = " xf_snippet_package";
$modversion['tables'] [4] = " xf_snippet_package_item";
$modversion['tables'] [5] = " xf_snippet_package_version";
$modversion['tables'] [6] = " xf_snippet_type";
$modversion['tables'] [7] = " xf_snippet_version";

// Admin things
$modversion['hasAdmin'] = 0;

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "snippet_search";
?>