<?php
if ( !defined("SURVEY_COMMON_INCLUDED") )
{
	define("SURVEY_COMMON_INCLUDED", 1);
	define("SURVEY_ADMIN_PAGE", 1);
	define("SURVEY_ADD_SURVEYS_PAGE", 2);
	define("SURVEY_BROWSE_SURVEYS_PAGE", 3);
	define("SURVEY_EDIT_SURVEYS_PAGE", 4);
	define("SURVEY_ADD_QUESTIONS_PAGE", 5);
	define("SURVEY_EDIT_QUESTIONS_PAGE", 6);
	define("SURVEY_SHOW_RESULTS_PAGE", 7);
}
?>